### ISSUE TITLE
Unable to pip install torch-cluster 

### ISSUE THREAD

**Issue by atharvabagde** [rusty1s/pytorch_cluster#209]
I am trying to replicate a GitHub repo and thus installing some older versions of packages.
I have create a virtualenv using Pyenv with :
Python: 3.7.12
torch:1.12.0
OS: MacOS M2 Sonoma 14.1
pip: 24.0

while trying to install torch-cluster using

pip install torch-cluster==1.5.9

I get the following error 

![Screenshot 2024-02-26 at 12 12 39 PM](https://github.com/rusty1s/pytorch_cluster/assets/49869216/3075b261-8dec-4a1a-bc70-ca3523a93618)

**Comment by rusty1s** [comment]
This is fixed on master via https://github.com/rusty1s/pytorch_cluster/pull/208. You can do
```python
pip install git+https://github.com/rusty1s/pytorch_cluster.git
```
for now

**Comment by hafizalsree** [comment]
Hi
I still have the same problem. 
I am trying to use unpool.knn_interpolate function via torch_geometric. I did not have to use torch-cluster previously, but it requires torch-cluster after updating the system.
Please assist.
