### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by jkuck** [rusty1s/pytorch_cluster#59]
This install (from the instructions) failed for me:

$ pip install torch-cluster==latest+cpu -f https://pytorch-geometric.com/whl/torch-1.4.0.html

But this worked:

$ pip install torch-cluster==latest+cpu -f https://s3.eu-central-1.amazonaws.com/pytorch-geometric.com/whl/torch-1.4.0.html

**Comment by rusty1s** [comment]
Fixed!

**Comment by jkuck** [comment]
Thanks for the quick check!  I'm actually still getting this error:

$ pip install torch-cluster==latest+cpu -f https://pytorch-geometric.com/whl/torch-1.4.0.html
Looking in links: https://pytorch-geometric.com/whl/torch-1.4.0.html
ERROR: Could not find a version that satisfies the requirement torch-cluster==latest+cpu (from versions: 0.1.1, 0.2.3, 0.2.4, 1.0.1, 1.0.3, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.3.0, 1.4.0, 1.4.1, 1.4.2, 1.4.3a1, 1.4.3, 1.4.4, 1.4.5)
ERROR: No matching distribution found for torch-cluster==latest+cpu

**Comment by rusty1s** [comment]
Can you try to upgrade pip to see whether this fixes the error?

**Comment by jkuck** [comment]
I'm still getting this error after upgrading pip.  I'm only getting this error when running on linux, it works for me when running on a mac.  I also get the error when running with cu92, cu100, and cu101.

**Comment by rusty1s** [comment]
Does it work when you directly install from the wheel link?

**Comment by jkuck** [comment]
Actually it works for me.  The problem seems to have been that I was running the command:

$ pip install torch-cluster==latest+cpu -f https://pytorch-geometric.com/whl/torch-1.4.0.html

inside a conda virtual environment.  Sorry for the trouble, but appreciate the help!
