### ISSUE TITLE
Bug in random_walk

### ISSUE THREAD

**Issue by cszhangzhen** [rusty1s/pytorch_cluster#81]
Hi,

I think the random_walk result is wrong when isolated nodes exist in the graph.

For example, 
```import torch
from torch_cluster import random_walk

row = torch.tensor([1, 1, 2, 2, 3, 3, 4, 4])
col = torch.tensor([2, 3, 1, 4, 1, 4, 2, 3])
start = torch.tensor([0, 1, 2, 3, 4])

walk = random_walk(row, col, start, walk_length=3)
```
in this situation, node 0 is an isolated node.

However, the result of random walk is 
```
tensor([[0, 2, 4, 2],
        [1, 2, 1, 3],
        [2, 4, 3, 4],
        [3, 1, 2, 1],
        [4, 2, 1, 2]])
```
The correct result in first line should be `[0,0,0,0]`. The current version seems to return random nodes in the graph.

More bug information, if we have a large graph(e.g., 66 nodes), and most of the nodes are isolated nodes, then it produces a segmentation fault (core dumped) error.

 ```
>>> import torch
>>> from torch_cluster import random_walk
>>> row = torch.tensor([21,21,27,29,54,54,60,62])
>>> col = torch.tensor([27,29,21,21,60,62,54,54])
>>> start = torch.arange(66)
>>> walk = random_walk(row, col, start, walk_length=5)
Segmentation fault (core dumped)
```

**Comment by rusty1s** [comment]
Thanks for reporting. It is fixed in master.

**Comment by cszhangzhen** [comment]
Thanks!

**Comment by wohlbier** [comment]
Was this fixed for cpu also?

I've got some code
```
rw = random_walk(
        data.edge_index[0], data.edge_index[1],
        node_idx, walk_length=walk_length,
        num_nodes=data.num_nodes)
rw_idx = rw[:, 1:].flatten()
```
I'm getting values in `rw_idx` that are greater than `data.num_nodes`. It seems like something is going out of bounds. I also have isolated nodes.

**Comment by rusty1s** [comment]
I will look into it.

**Comment by wohlbier** [comment]
Please see my comment here
https://github.com/rusty1s/pytorch_geometric/pull/1514/commits/4f1956b90f3e9ed61927b23e27ab48fe064b1356
for a possible reproducer. If you cannot reproduce, I can get you a specific dataset where I'm seeing it.

**Comment by wohlbier** [comment]
Screenshot of the comment if you don't see it.
<img width="1025" alt="Screen Shot 2020-09-22 at 2 16 15 PM" src="https://user-images.githubusercontent.com/8867238/93927259-3c21aa80-fcde-11ea-8ac5-67c7e0cde4b3.png">

**Comment by rusty1s** [comment]
I will try to reproduce and fix this tomorrow. In the meantime, you can easily fix that by yourself by adding self-loops to your graph for all isolated nodes.

**Comment by rusty1s** [comment]
This is now *really* fixed in master. Sorry for any inconveniences!

**Comment by ZhuYun97** [comment]
I still meet this bug using (torch-cluster 1.5.9). I have tried to uninstall _torch-cluster_ and install it from the master branch. But it does not work. 
Adding self-loops can solve this bug, but it will lead to the target nodes including the source node, e.g. 0->(0, neighbors of 0). The probability of choosing the next node is not the same as the naive random walk.

Which version should I use? Waiting for your help.

```
edges = torch.tensor([[1,2], [2,1]])
x = torch.ones([5,5])
g = Data(x = x, edge_index=edges)
row = edges[0]
col = edges[1]
random_walk(row, col, torch.tensor([4]), 10)
------
59148 segmentation fault (core dumped)
```

**Comment by g-morishita** [comment]
Has the segmentation fault been fixed? I still encountered this segmentation fault. Should I open a new issue to give the details?

Thanks.

**Comment by rusty1s** [comment]
I think so, in case you do not prove me wrong :)

You can create another issue with a minimal example to reproduce. This would be great.
